var classes = [
    {
        "name": "Markani\\Tugas1\\App\\Algorithm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "quickSort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "insertionSort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 8,
        "ccnMethodMax": 5,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 91,
        "vocabulary": 26,
        "volume": 427.74,
        "difficulty": 25.71,
        "effort": 10999.03,
        "level": 0.04,
        "bugs": 0.14,
        "time": 611,
        "intelligentContent": 16.63,
        "number_operators": 31,
        "number_operands": 60,
        "number_operators_unique": 12,
        "number_operands_unique": 14,
        "cloc": 1,
        "loc": 40,
        "lloc": 39,
        "mi": 57.92,
        "mIwoC": 45.79,
        "commentWeight": 12.13,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 6,
        "package": "Markani\\Tugas1\\App\\",
        "pageRank": 1,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]