var classes = [
    {
        "name": "Markani\\Tugas1\\App\\Algorithm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "selectionSort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "insertionSort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 8,
        "ccnMethodMax": 5,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 97,
        "vocabulary": 20,
        "volume": 419.23,
        "difficulty": 48,
        "effort": 20122.9,
        "level": 0.02,
        "bugs": 0.14,
        "time": 1118,
        "intelligentContent": 8.73,
        "number_operators": 33,
        "number_operands": 64,
        "number_operators_unique": 12,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 34,
        "lloc": 34,
        "mi": 47.15,
        "mIwoC": 47.15,
        "commentWeight": 0,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "package": "Markani\\Tugas1\\App\\",
        "pageRank": 1,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]